# docker-compose.yml
services:
  # Development service
  marketpulse-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3004:3000"
    environment:
      # Supabase Configuration
      NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}

      # Site Configuration
      NEXT_PUBLIC_SITE_URL: http://localhost:3004

      # Stripe Configuration
      NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}

      

      # Discord Configuration
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      DISCORD_REDIRECT_URI: ${DISCORD_REDIRECT_URI}
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      DISCORD_GUILD_ID: ${DISCORD_GUILD_ID}
      DISCORD_ROLE_FREE: ${DISCORD_ROLE_FREE}
      DISCORD_ROLE_PRO: ${DISCORD_ROLE_PRO}
      DISCORD_ROLE_PREMIUM: ${DISCORD_ROLE_PREMIUM}

      # AI Configuration
      GOOGLE_AI_API_KEY: ${GOOGLE_AI_API_KEY}

      # Development Settings
      NODE_ENV: development
      NEXT_TELEMETRY_DISABLED: 1
      DISABLE_AUTH_MIDDLEWARE: true
    volumes:
      # Mount source code for hot reloading
      - .:/app
      # Prevent node_modules from being overwritten
      - /app/node_modules
      - /app/.next
    networks:
      - marketpulse-network
    restart: unless-stopped
  # Production service (commented out by default)
  # marketpulse-prod:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3002:3000"
  #   environment:
  #     # Environment variables loaded from .env files
  #     NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
  #     NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
  #     SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
  #     NEXT_PUBLIC_SITE_URL: http://localhost:3002
  #     NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
  #     STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
  #     STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
  #     # AI Configuration
  #     GOOGLE_AI_API_KEY: ${GOOGLE_AI_API_KEY}
  #     NODE_ENV: production
  #     NEXT_TELEMETRY_DISABLED: 1
  #   networks:
  #     - marketpulse-network
  #   restart: unless-stopped

networks:
  marketpulse-network:
    driver: bridge
